name: Tests

on: workflow_dispatch

env:
  AUDIO_URL: https://rayquaza.lw997.usbx.me/files/Friends.S01.1080p.BluRay.x264-TENEIGHTY%5Brartv%5D/friends-s1e1-audio.mp4
  VIDEO_URL: https://test
  DOWNLOAD_USERNAME: ${{ secrets.DOWNLOAD_USERNAME }}
  DOWNLOAD_PASSWORD: ${{ secrets.DOWNLOAD_PASSWORD }}
  MEDIA_KEY: e7
  FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

jobs:
  encode-audio:
    name: Encode Audio
    runs-on: ubuntu-20.04

    steps:
      - name: Encode Audio
        run: |
          curl -u "$DOWNLOAD_USERNAME:$DOWNLOAD_PASSWORD" "$AUDIO_URL" --output media --no-progress-meter
          apt-get update > /dev/null
          apt-get install xz-utils ncftp > /dev/null
          curl --location https://github.com/sateshpersaud/ffmpeg/releases/download/2021-04-14-2/ffmpeg.xz --output ffmpeg.xz --no-progress-meter
          xz --decompress ffmpeg.xz
          chmod +x ffmpeg
          mkdir --parents output
          ./ffmpeg -hide_banner -loglevel warning -i media -map 0:a:0 -codec:a:0 libopus -ac:a:0 2 -b:a:0 64k -map_metadata:g -1 -map_metadata:s:a:0 -1 -fflags +bitexact -flags:a:0 +bitexact -dash_segment_type mp4 -format_options movflags=skip_sidx:empty_hdlr_name=1 -seg_duration 10 -frag_duration 10 -init_seg_name 0 -media_seg_name '$Number$' -use_timeline 0 -hls_playlist 1 -f dash output/manifest.mpd
          ncftpput -V -z -m -u "$FTP_USERNAME" -p "$FTP_PASSWORD" ny.storage.bunnycdn.com "$MEDIA_KEY/a" output/*
