on: workflow_dispatch

env:
  MEDIA_ID: m1
  MEDIA_URL: https://rayquaza.lw997.usbx.me/files/Mortal.Kombat.2021.1080p.WEBRip.DD5.1.x264-CM/Mortal.Kombat.2021.1080p.WEBRip.DD5.1.x264-CM.mkv
  USB_HTTP_USERNAME: ${{ secrets.USB_HTTP_USERNAME }}
  USB_HTTP_PASSWORD: ${{ secrets.USB_HTTP_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  EC2_METADATA_DISABLED: true
  AWS_DEFAULT_REGION: 'us-east-1'

jobs:
  get-media-info:
    runs-on: ubuntu-20.04

    steps:
      - run: |
          curl --user $USB_HTTP_USERNAME:$USB_HTTP_PASSWORD  "$MEDIA_URL" --output $MEDIA_ID --no-progress-meter
          sudo apt-get update > /dev/null
          sudo apt-get install ffmpeg awscli > /dev/null
          ffprobe -v quiet -print_format json -show_format -show_streams $MEDIA_ID
          aws s3 cp $MEDIA_ID s3://astro-gnk-0001/$MEDIA_ID --endpoint-url=https://s3.wasabisys.com
